# Generated by Django 6.1.1 on 2026-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('answered_questions', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
